package org.srcm.heartfulness.repository;

import org.srcm.heartfulness.model.Program;
import org.srcm.heartfulness.model.ProgramCoordinators;
import org.srcm.heartfulness.model.SecondaryCoordinatorRequest;
import org.srcm.heartfulness.model.User;

/**
 * 
 * @author himasreev
 *
 */
public interface CoordinatorAccessControlRepository {

	Program getProgramIdByEventId(String autoGeneratedEventId);

	User getUserbyUserEmail(String userEmail);

	void saveSecondaryCoordinatorRequest(SecondaryCoordinatorRequest scReq);

	void savecoordinatorDetails(ProgramCoordinators programCoordinators);
	
	int checkRequestAlreadyRaised(int programId, String userEmail);
	
	int checkRequestAlreadyApproved(int programId, String userEmail);

	int approveSecondaryCoordinatorRequest(int programId, String approvedBy, String requestedBy);

	void createProgramCoordinator(ProgramCoordinators pgrmCoordinators);

	

	
	
	

}
