package org.srcm.heartfulness.repository;

import java.util.Collection;
import java.util.Date;
import java.util.List;

import org.springframework.dao.DataAccessException;
import org.srcm.heartfulness.model.Participant;
import org.srcm.heartfulness.model.Program;
import org.srcm.heartfulness.model.json.request.EventAdminChangeRequest;

/**
 * Repository class for <code>Program</code> domain class.
 *
 * @author Venkat Sonnathi
 */
public interface ProgramRepository {

    /**
     * Retrieve <code>Program</code>s from the data store by hashCode.
     *
     * @param hashCode Value to search for
     * @return a <code>Collection</code> of matching <code>Owner</code>s (or an empty <code>Collection</code> if none
     * found)
     */
    Collection<Program> findByHashCode(String hashCode) throws DataAccessException;

    /**
     * Retrieve a <code>Program</code> from the data store by id.
     *
     * @param id the id to search for
     * @return the <code>Program</code> if found
     * @throws org.springframework.dao.DataRetrievalFailureException if not found
     */
    Program findById(int id) throws DataAccessException;

    /**
     * Retrieve <code>Program</code> objects that are modified after a given date.
     *
     * @param lastBatchRun the date to compare modified time for the program objects.
     * @return the list of program ids (not the full object)
     */
    List<Integer> findUpdatedProgramIdsSince(Date lastBatchRun);

    /**
     * Save an <code>Program</code> to the data store, either inserting or updating it.
     */
    void save(Program program);
    
    /**
     * To check whether the program exists or not
     * 
     * @param program - the <code>Program</code>
     * @return the boolean(true or false)
     */
    boolean isProgramExist(Program program);
    
    /**
     * Retrieve a <code>Program</code> from the data store by Auto generated Event ID
     * 
     * @param autoGeneratedEventId - Auto generated Event ID to search for
     * @return the <code>Program</code> if found
     */
	Program findByAutoGeneratedEventId(String autoGeneratedEventId);
	
	/**
     * Retrieve a <code>Program</code> from the data by Auto generated Event ID
     * 
     * @param autoGeneratedIntroId - Auto generated Introduction ID to search for
     * @return the <code>Program</code> if found
     */
	Program findByAutoGeneratedIntroId(String autoGeneratedIntroId);
	
	/**
     * Retrieve a <code>Program</code> from the data by Auto generated Event ID
     * 
     * @param eventName - Event Name to search for
     * @return the <code>Program</code> if found
     */
	Program findByEventName(String eventName);
	
	List<Program> getEventByEmail(String email,boolean isAdmin);
	
	boolean isProgramExistByProgramName(Program program);

	void saveWithProgramName(Program program);
	

	Program getEventById(int id);

	List<Participant> getParticipantList(int decryptedProgramId);
	
	/**
	 * Get the list of programs depending on the coordinator email and 
	 * whether he is admin or not.
	 * @param email
	 * @param isAdmin
	 * @return 
	 */
	List<Program> getEventsByEmail(String email,boolean isAdmin);
	
	/**
	 * Repository method to create a new record or update an existing event record. 
	 * @param event to persist into the database.
	 * @return Program
	 */
	Program saveProgram(Program program);
	
	int getProgramIdByEventId(String eventID);
	
	int getEventCountByEmail(String email, boolean isAdmin);

	int getNonCategorizedEventsByEmail(String email, boolean isAdmin);

	Participant findParticipantBySeqId(String seqId, int programId);
	
	void UpdateParticipantsStatus(String participantIds, String eventId ,String introduced);
	
	List<String> getAllEventCategories();
	
	int getEventCountByCategory(String email, boolean isAdmin, String eventCategory);

	int getMiscellaneousEventsByEmail(String email, boolean isAdmin, List<String> eventcategories);
	
	void updateCoOrdinatorStatistics(EventAdminChangeRequest eventAdminChangeRequest);

}
