
-- --------------------------------------------------
-- Staging table from here
# DROP TABLE IF EXISTS `program`;

CREATE TABLE IF NOT EXISTS `program` (
  `program_id` int(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `program_hash_code` varchar(50) NULL,
  `program_channel` varchar(150) DEFAULT NULL,
  `program_start_date` date DEFAULT NULL,
  `program_end_date` date DEFAULT NULL,
  `event_place` varchar(150) DEFAULT NULL,
  `event_city` varchar(150) DEFAULT NULL,
  `event_state` varchar(150) DEFAULT NULL,
  `event_country` varchar(50) DEFAULT NULL,
  `coordinator_name` varchar(150) DEFAULT NULL,
  `coordinator_email` varchar(150) DEFAULT NULL,
  `coordinator_mobile` varchar(150) DEFAULT NULL,
  `organization_name` VARCHAR(150) DEFAULT NULL,
  `organization_department` varchar(45) DEFAULT NULL,
  `organization_web_site` varchar(150) DEFAULT NULL,
  `organization_contact_name` varchar(100) DEFAULT NULL,
  `organization_contact_email` varchar(100) DEFAULT NULL,
  `organization_contact_mobile` varchar(25) DEFAULT NULL,
  `preceptor_name` varchar(45) DEFAULT NULL,
  `preceptor_id_card_number` varchar(45) DEFAULT NULL,
  `welcome_card_signed_by_name` varchar(45) DEFAULT NULL,
  `welcome_card_signer_id_card_number` varchar(45) DEFAULT NULL,
  `remarks` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `updated_by` varchar(45) DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `seeker_aims` (
  `First_Name` varchar(150) DEFAULT NULL,
  `Last_Name` varchar(150) DEFAULT NULL,
  `Middle_Name` varchar(50) DEFAULT NULL,
  `Email` varchar(250) DEFAULT NULL,
  `Phone_Mobile` varchar(25) DEFAULT NULL,
  `Gender` int(11) DEFAULT NULL,
  `Date_of_Birth` date DEFAULT NULL,
  `Date_of_Registration` date DEFAULT NULL,
  `Abhyasi_ID` varchar(100) DEFAULT NULL,
  `Status` tinyint(1) DEFAULT '0' COMMENT '0 means Active\\n1 means Inactive',
  `Address_Line_1` varchar(150) DEFAULT NULL,
  `Address_Line_2` varchar(150) DEFAULT NULL,
  `City` varchar(50) DEFAULT NULL,
  `State` varchar(50) DEFAULT NULL,
  `Country` varchar(50) DEFAULT NULL,
  `Seeker_ID` int(11) NOT NULL,
  `Program_id` int(11) NOT NULL,
  `Occupation` varchar(50) DEFAULT NULL,
  `Remarks` varchar(500) DEFAULT NULL,
  `ID_Card_Num` varchar(45) DEFAULT NULL,
  `Language` varchar(45) DEFAULT NULL,
  `Sync_Status` varchar(45) DEFAULT NULL,
  `Introduced` tinyint(1) DEFAULT '0' COMMENT '0 means No   and 1 means Yes',
  `Introduced_Date` date DEFAULT NULL,
  `Introduced_raw_date` varchar(50) DEFAULT NULL,
  `Introduced_By` varchar(75) DEFAULT NULL,
  `Welcome_Card_Num` varchar(45) DEFAULT NULL,
  `Welcome_Card_Date` date DEFAULT NULL,
  `Age_Group` varchar(45) DEFAULT NULL,
  `Upload_Status` tinyint(1) DEFAULT '0' COMMENT '0 Means Uploaded, 1 means De-Dup done, 2- Normalized, 3 - Synced to AIMS',
  `first_sitting` int(11) DEFAULT NULL,
  `second_sitting` int(11) DEFAULT NULL,
  `third_sitting` int(11) DEFAULT NULL,
  `first_sitting_date` date DEFAULT NULL,
  `second_sitting_date` date DEFAULT NULL,
  `third_sitting_date` date DEFAULT NULL,
  `occupation_stream` varchar(50) DEFAULT NULL,
  `batch` varchar(50) DEFAULT NULL,
  `receive_updates` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`Seeker_ID`),
  KEY `ProgramId_FK` (`Program_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
