package org.srcm.heartfulness.webservice;

import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.core.Context;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.HttpClientErrorException;
import org.srcm.heartfulness.constants.ErrorConstants;
import org.srcm.heartfulness.constants.PMPConstants;
import org.srcm.heartfulness.encryption.decryption.AESEncryptDecrypt;
import org.srcm.heartfulness.model.User;
import org.srcm.heartfulness.model.json.request.Event;
import org.srcm.heartfulness.model.json.request.EventAdminChangeRequest;
import org.srcm.heartfulness.model.json.request.SearchRequest;
import org.srcm.heartfulness.model.json.response.ErrorResponse;
import org.srcm.heartfulness.model.json.response.UserProfile;
import org.srcm.heartfulness.service.APIAccessLogService;
import org.srcm.heartfulness.service.ProgramService;
import org.srcm.heartfulness.service.UserProfileService;
import org.srcm.heartfulness.util.DateUtils;
import org.srcm.heartfulness.validator.EventDashboardValidator;

import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;

@RestController
@RequestMapping("/api/event")
public class EventsController {

	private static final Logger LOGGER = LoggerFactory.getLogger(EventsController.class);

	@Autowired
	private ProgramService programService;

	@Autowired
	Environment env;

	@Autowired
	private AESEncryptDecrypt aesEncryptDecrypt;

	@Autowired
	EventDashboardValidator eventDashboardValidator;

	@Autowired
	private UserProfileService userProfileService;

	@Autowired
	APIAccessLogService apiAccessLogService;

	/**
	 * Web service endpoint to fetch a particular event.
	 * 
	 * If the event is found successfully, the service returns an success
	 * response body with HTTP status 200.
	 * 
	 * If the event is not found, the service returns response with status
	 * failed with HTTP status 200.
	 * 
	 * If some exception is raised while processing the request, error response
	 * is returned with respective HttpStatus code.
	 * 
	 * @param token
	 *            ,Token to be validated against MySRCM endpoint.
	 * @param event
	 * @return A ResponseEntity containing success message, if created
	 *         successfully, and a HTTP status code as described in the method
	 *         comment.
	 */
	@RequestMapping(value = "/geteventdetails", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> getEventDetails(@RequestHeader(value = "Authorization") String token,
			@RequestBody Event event, @Context HttpServletRequest httpRequest) throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			LOGGER.debug("Trying to fetch event details for eventID : {} ", event.getAutoGeneratedEventId());
			Event eventdetails = new Event();
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}
			Map<String, String> errors = new HashMap<String, String>();
			if (null == event.getAutoGeneratedEventId() || event.getAutoGeneratedEventId().isEmpty()) {
				errors.put("eventId", "Invalid Event ID");
				eventdetails.setErrors(errors);
				eventdetails.setStatus(ErrorConstants.STATUS_FAILED);
			} else {
				int programId = programService.getProgramIdByEventId(event.getAutoGeneratedEventId());
				if (programId > 0) {
					eventdetails = programService.getEventDetails(event.getAutoGeneratedEventId());
				} else {
					errors.put("eventId", "Event Id doesnot exist");
					eventdetails.setErrors(errors);
					eventdetails.setStatus(ErrorConstants.STATUS_FAILED);
				}
			}
			LOGGER.debug("Fetched event details for eventID : {} ", event.getAutoGeneratedEventId());
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<Event>(eventdetails, HttpStatus.OK);

		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

	/**
	 * Web service endpoint to fetch list of events.
	 * 
	 * If list of events are found successfully, the service returns an success
	 * response body with HTTP status 200.
	 * 
	 * If list of events are not found, the service returns an empty response
	 * body with HTTP status 200.
	 * 
	 * If some exception is raised while processing the request, error response
	 * is returned with respective HttpStatus code.
	 * 
	 * @param token
	 *            ,Token to be validated against MySRCM endpoint.
	 * @return A ResponseEntity containing success message, if created
	 *         successfully, and a HTTP status code as described in the method
	 *         comment.
	 */
	@RequestMapping(value = "/geteventlist", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> getEventList(@RequestHeader(value = "Authorization") String token,
			@Context HttpServletRequest httpRequest) throws ParseException {
		List<Event> eventList = new ArrayList<>();
		boolean isAdmin = false;
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			LOGGER.debug("Trying to get event list for logged in user");
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}

			User user = userProfileService.loadUserByEmail(userProfile.getEmail());
			if (null == user) {
				LOGGER.debug("UserProfile doesnot exists in PMP database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
						"User doesnot exists in PMP database");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
			}

			if (PMPConstants.LOGIN_ROLE_ADMIN.equals(user.getRole())) {
				isAdmin = true;
			}
			eventList = programService.getEventListByEmail(user.getEmail(), isAdmin);
			LOGGER.debug("Trying to get event list for logged in user");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<List<Event>>(eventList, HttpStatus.OK);
		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			e.printStackTrace();
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

	/**
	 * Web service endpoint to create an event.
	 * 
	 * If event is created successfully, the service returns an event with
	 * eventId in response body with HTTP status 200.
	 * 
	 * If some exception is raised while processing the request, error response
	 * is returned with respective HttpStatus code.
	 * 
	 * @param Event
	 *            to create an event in the pmp database.
	 * @param token
	 *            Token to be validated against MySRCM endpoint.
	 * @return A ResponseEntity containing success message if found, and a HTTP
	 *         status code as described in the method comment.
	 * @param program
	 * @param token
	 * @return
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> createProgram(@RequestBody Event event,
			@RequestHeader(value = "Authorization") String token, @Context HttpServletRequest httpRequest)
			throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {

			List<Event> eventList = new ArrayList<Event>();
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}

			eventList.add(event);
			programService.createOrUpdateEvent(eventList);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<Event>(event, HttpStatus.OK);

		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

	/**
	 * Web service endpoint to update event.
	 * 
	 * If event is updated successfully, the service returns an success message
	 * in response body with HTTP status 200.
	 * 
	 * 
	 * If some exception is raised while processing the request, error response
	 * is returned with respective HttpStatus code.
	 * 
	 * @param Event
	 *            to update an existing event in the pmp database.
	 * @param token
	 *            Token to be validated against MySRCM endpoint.
	 * @return A ResponseEntity containing success message if found, and a HTTP
	 *         status code as described in the method comment.
	 * @param program
	 * @param token
	 * @return
	 */
	@RequestMapping(value = "/update", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> updateProgram(@RequestBody Event event,
			@RequestHeader(value = "Authorization") String token, @Context HttpServletRequest httpRequest)
			throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {

			List<Event> eventList = new ArrayList<Event>();
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}
			Map<String, String> errors = new HashMap<String, String>();
			if (null == event.getAutoGeneratedEventId() || event.getAutoGeneratedEventId().isEmpty()) {
				errors.put("eventId", "Invalid Event ID");
				event.setErrors(errors);
				event.setStatus(ErrorConstants.STATUS_FAILED);
			} else {

				int programId = programService.getProgramIdByEventId(event.getAutoGeneratedEventId());
				if (programId > 0) {
					eventList.add(event);
					programService.createOrUpdateEvent(eventList);
				} else {
					errors.put("eventId", "Event ID does not exists");
					event.setErrors(errors);
					event.setStatus(ErrorConstants.STATUS_FAILED);
				}
			}
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<Event>(event, HttpStatus.OK);

		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

	/**
	 * 
	 * Web service endpoint to update list of events .
	 * 
	 * If event is updated successfully status is set to Success else to Failed
	 * and the service returns a list of events with HTTP status 200.
	 * 
	 * 
	 * If some exception is raised while processing the request, error response
	 * is returned with respective HttpStatus code.
	 * 
	 * @param events
	 *            List of events to be updated.
	 * @param token
	 *            Need to be authenticated against MySRCM.
	 * @return list of events with success ot failed status.
	 */

	@RequestMapping(value = "/updateevents", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> updatePrograms(@RequestBody List<Event> events,
			@RequestHeader(value = "Authorization") String token, @Context HttpServletRequest httpRequest)
			throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}

			List<Event> eventList = new ArrayList<>();
			for (Event event : events) {
				Map<String, String> errors = new HashMap<String, String>();
				if (null == event.getAutoGeneratedEventId() || event.getAutoGeneratedEventId().isEmpty()) {
					errors.put("eventId", "Invalid Event ID");
					event.setErrors(errors);
					event.setStatus(ErrorConstants.STATUS_FAILED);
					eventList.add(event);
				} else {
					int programId = programService.getProgramIdByEventId(event.getAutoGeneratedEventId());
					if (programId > 0) {
						List<Event> eventsList = new ArrayList<>();
						eventsList.add(event);
						eventList.addAll(programService.createOrUpdateEvent(eventsList));
					} else {
						errors.put("eventId", "Event ID does not exists");
						event.setErrors(errors);
						event.setStatus(ErrorConstants.STATUS_FAILED);
						eventList.add(event);
					}
				}
			}
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<List<Event>>(eventList, HttpStatus.OK);

		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

	@RequestMapping(value = "/updateeventadmin", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> updateEventAdmin(@RequestHeader(value = "Authorization") String token,
			@RequestBody EventAdminChangeRequest eventAdminChangeRequest, @Context HttpServletRequest httpRequest)
			throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
			} else {
				Map<String, String> map = eventDashboardValidator
						.checkUpdateEventAdminMandatoryFields(eventAdminChangeRequest);
				if (!map.isEmpty()) {
					apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
							httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
					return new ResponseEntity<Map<String, String>>(map, HttpStatus.PRECONDITION_FAILED);
				} else {
					eventAdminChangeRequest.setCreatedBy(userProfile.getEmail());
					programService.updateEventAdmin(eventAdminChangeRequest);
					programService.updateCoOrdinatorStatistics(eventAdminChangeRequest);
					apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
							httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
					return new ResponseEntity<EventAdminChangeRequest>(eventAdminChangeRequest, HttpStatus.OK);
				}
			}
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"parse-error : error while parsing json data");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"json mapping-error : json data is not mapped properly");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"input/output-error ; Please try after sometime");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Please try after sometime.");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.INTERNAL_SERVER_ERROR);
		}

	}

	/**
	 * Web service endpoint to the get the events count by category based on
	 * logged in user.
	 * 
	 * @param token
	 *            is for the authorizing the user and gets the user profile from
	 *            the token
	 * @return ResponseEntity containing status and its description based on
	 *         deletion, and a HTTP status code as described in the method
	 *         comment.
	 */
	@RequestMapping(value = "/geteventcountbycategory", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> geteventCountByCategory(@RequestHeader(value = "Authorization") String token,
			@Context HttpServletRequest httpRequest) throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			boolean isAdmin = false;
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
			} else {
				User user = userProfileService.loadUserByEmail(userProfile.getEmail());
				if (null != user && PMPConstants.LOGIN_ROLE_ADMIN.equalsIgnoreCase(user.getRole())) {
					isAdmin = true;
				}
				Map<String, Integer> resultMap = new HashMap<String, Integer>();
				List<String> Eventcategories = programService.getAllEventCategories();
				resultMap.put(PMPConstants.TOTAL_EVENTS,
						programService.getEventCountByEmail(userProfile.getEmail(), isAdmin));
				resultMap.put(PMPConstants.UN_CATEGORIZED,
						programService.getNonCategorizedEventsByEmail(userProfile.getEmail(), isAdmin));
				for (String eventCategory : Eventcategories) {
					resultMap.put(eventCategory.toUpperCase(),
							programService.getEventCountByCategory(userProfile.getEmail(), isAdmin, eventCategory));
				}
				resultMap.put(PMPConstants.MISCELLANEOUS,
						programService.getMiscellaneousEventsByEmail(userProfile.getEmail(), isAdmin, Eventcategories));
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<Map<String, Integer>>(resultMap, HttpStatus.OK);

			}
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"parse-error : error while parsing json data");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"json mapping-error : json data is not mapped properly");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"input/output-error ; Please try after sometime");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Please try after sometime.");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}

	/**
	 * web service endpoint to search the events based on search field and text
	 * given.
	 * 
	 * @param token
	 * @param searchRequest
	 * @return
	 */
	@RequestMapping(value = "/search", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> searchEvents(@RequestHeader(value = "Authorization") String token,
			@RequestBody SearchRequest searchRequest, @Context HttpServletRequest httpRequest) throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			List<Event> eventList = new ArrayList<>();
			userProfile=eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
			} else {
				eventList = programService.searchEvents(searchRequest);
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<List<Event>>(eventList, HttpStatus.OK);
			}
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"client-error : Invalid auth token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.REQUEST_TIMEOUT);
		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			ErrorResponse error = new ErrorResponse(ErrorConstants.STATUS_FAILED, ErrorConstants.INVALID_AUTH_TOKEN);
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(error, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"parse-error : error while parsing json data");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"json mapping-error : json data is not mapped properly");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"input/output-error ; Please try after sometime");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Please try after sometime.");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.INTERNAL_SERVER_ERROR);
		}
	}

	@RequestMapping(value = "/fetcheventdetails", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<?> getEventDetailsWithDecryptedID(@RequestHeader(value = "Authorization") String token,
			@RequestBody Event event, @Context HttpServletRequest httpRequest) throws ParseException {
		String requestTime = DateUtils.getCurrentTimeInMilliSec();
		UserProfile userProfile = null;
		try {
			Event eventdetails = new Event();
			userProfile = eventDashboardValidator.validateToken(token);
			if (null == userProfile) {
				LOGGER.debug("UserProfile doesnot exists in MySrcm database");
				ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid auth token.");
				apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
						httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
				return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
			}
			Map<String, String> errors = new HashMap<String, String>();
			if (null == event.getAutoGeneratedEventId() || event.getAutoGeneratedEventId().isEmpty()) {
				errors.put("eventId", "Invalid Event ID");
				eventdetails.setErrors(errors);
				eventdetails.setStatus(ErrorConstants.STATUS_FAILED);
			} else {
				int programId = programService.getProgramIdByEventId(aesEncryptDecrypt.decrypt(
						event.getAutoGeneratedEventId(), env.getProperty(PMPConstants.SECURITY_TOKEN_KEY)));
				if (programId > 0) {
					eventdetails = programService.getEventDetails(aesEncryptDecrypt.decrypt(
							event.getAutoGeneratedEventId(), env.getProperty(PMPConstants.SECURITY_TOKEN_KEY)));
				} else {
					errors.put("eventId", "Event Id doesnot exist");
					eventdetails.setErrors(errors);
					eventdetails.setStatus(ErrorConstants.STATUS_FAILED);
				}
			}
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<Event>(eventdetails, HttpStatus.OK);

		} catch (IllegalBlockSizeException | NumberFormatException | BadPaddingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid authorization token");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (HttpClientErrorException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid client credentials");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.UNAUTHORIZED);
		} catch (JsonParseException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (JsonMappingException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (IOException e) {
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED,
					"Error while fetching profile from MySRCM");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		} catch (Exception e) {
			e.printStackTrace();
			LOGGER.error("Exception    :" + e.getMessage());
			ErrorResponse eResponse = new ErrorResponse(ErrorConstants.STATUS_FAILED, "Invalid request");
			apiAccessLogService.createLogDetails((null == userProfile ? null : userProfile.getEmail()),
					httpRequest.getRemoteAddr(), httpRequest.getRequestURI(), requestTime);
			return new ResponseEntity<ErrorResponse>(eResponse, HttpStatus.BAD_REQUEST);
		}
	}

}
