package org.srcm.heartfulness.webservice;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.web.bind.annotation.RestController;
import org.srcm.heartfulness.constants.EmailLogConstants;
import org.srcm.heartfulness.constants.ErrorConstants;
import org.srcm.heartfulness.constants.PMPConstants;
import org.srcm.heartfulness.helper.EWelcomeIDGenerationHelper;
import org.srcm.heartfulness.mail.SendMail;
import org.srcm.heartfulness.model.PMPAPIAccessLog;
import org.srcm.heartfulness.model.Participant;
import org.srcm.heartfulness.model.Program;
import org.srcm.heartfulness.repository.ParticipantRepository;
import org.srcm.heartfulness.repository.ProgramRepository;
import org.srcm.heartfulness.rest.template.AmazonSqsRestTemplate;
import org.srcm.heartfulness.service.APIAccessLogService;
import org.srcm.heartfulness.service.PmpParticipantService;
import org.srcm.heartfulness.service.ProgramService;
import org.srcm.heartfulness.util.DateUtils;
import org.srcm.heartfulness.util.StackTraceUtils;

import com.amazonaws.services.sqs.model.Message;

/**
 * Controller for managing ewelcomeId related functionalities.
 * 
 * @author himasreev
 *
 */
@RestController
public class EWelcomeIDGenerationScheduler {

	private static Logger LOGGER = LoggerFactory.getLogger(EWelcomeIDGenerationScheduler.class);

	@Autowired
	PmpParticipantService participantService;

	@Autowired
	ParticipantRepository participantRepository;

	@Autowired
	EWelcomeIDGenerationHelper eWelcomeIDGenerationHelper;

	@Autowired
	ProgramService programService;

	@Autowired
	APIAccessLogService apiAccessLogService;

	@Autowired
	SendMail sendMail;

	@Autowired
	private AmazonSqsRestTemplate amazonSqsRestTemplate;

	@Autowired
	private ProgramRepository pgrmRepository;

	/**
	 * Cron to generate EWelcomeIDs for the participants.
	 */
	/*@Scheduled(cron = "${welcome.mailids.generation.cron.time}")*/ 
	public void generateEWelcomeIDsForParticipants(List<Integer> programIds, Message message, String queueUrl) {

		if (!programIds.isEmpty() && programIds.size() > 0) {
			for (Integer programId : programIds) {
				List<Participant> participants = participantRepository.getParticipantwithProgramIdToGenerateEwelcomeId(programId);
				Program program = programService.getProgramDetailsToGenerateEwelcomeIDById(programId);

				LOGGER.info(
						"EWELCOMEID GENERATION : EventID: {} - Total no. of participants to generate eWelcomeID : {} ",
						program.getAutoGeneratedEventId(), participants.size());

				for (Participant participant : participants) {
					participant.setProgram(program);
					PMPAPIAccessLog pmpApiAccessLog = createPMPAPIAccessLog(null,null,StackTraceUtils.convertPojoToJson(participant));
					try {
						pmpApiAccessLog.setUsername(program.getCoordinatorEmail());
						participant.setProgram(program);
						String isvalid = null;
						if (0 == program.getFirstSittingBy()) {
							isvalid = programService.validatePreceptorIDCardNumber(program, pmpApiAccessLog.getId());
						}
						if (null == isvalid) {
							String eWelcomeID = programService.generateeWelcomeID(participant,  pmpApiAccessLog.getId());
							if ("success".equalsIgnoreCase(eWelcomeID)) {
								String responseBody = "Email:" + participant.getEmail() + " ,EventID:"
										+ participant.getProgram().getAutoGeneratedEventId() + " ,SeqId:"
										+ participant.getSeqId() + " ,EwelcomeID:" + participant.getWelcomeCardNumber()
										+ " ,Issued Date:" + participant.getWelcomeCardDate() + " ,EwelcomeID State:"
										+ participant.getEwelcomeIdState() + " ,EwelcomeID informed:"
										+ participant.getIsEwelcomeIdInformed();
								updatePMPAPIAccessLog(pmpApiAccessLog, ErrorConstants.STATUS_SUCCESS, null, responseBody);
							} else {
								eWelcomeID = transformErrorMsg(eWelcomeID);
								try {
									participant.setEwelcomeIdRemarks(eWelcomeID);
									participant.setEwelcomeIdState(PMPConstants.EWELCOMEID_FAILED_STATE);
									participant.setIsEwelcomeIdInformed(0);
									participantRepository.updateParticipantEwelcomeIDDetails(participant);
								} catch (Exception e) {
									LOGGER.error("Exception while persisting participant details : {} ",
											StackTraceUtils.convertPojoToJson(e));
								}
								String responseBody = "Email:" + participant.getEmail() + " ,EventID:"
										+ participant.getProgram().getAutoGeneratedEventId() + " ,SeqId:"
										+ participant.getSeqId() + " ,EwelcomeID State:"
										+ participant.getEwelcomeIdState() + " ,EwelcomeID informed:"
										+ participant.getIsEwelcomeIdInformed();
								updatePMPAPIAccessLog(pmpApiAccessLog, ErrorConstants.STATUS_FAILED, eWelcomeID, responseBody);
							}
						} else {
							try {
								for (Participant participant2 : participants) {
									participant2.setEwelcomeIdRemarks(isvalid);
									participant2.setEwelcomeIdState(PMPConstants.EWELCOMEID_FAILED_STATE);
									participant2.setIsEwelcomeIdInformed(0);
									participantRepository.updateParticipantEwelcomeIDDetails(participant2);
								}
								break;
							} catch (Exception e) {
								LOGGER.error("Exception while persisting participant details : {} ",StackTraceUtils.convertPojoToJson(e));
							}
							String responseBody = "Email:" + participant.getEmail() + " ,EventID:"
									+ participant.getProgram().getAutoGeneratedEventId() + " ,SeqId:"
									+ participant.getSeqId() + " ,EwelcomeID State:" + participant.getEwelcomeIdState()
									+ " ,EwelcomeID informed:" + participant.getIsEwelcomeIdInformed();
							updatePMPAPIAccessLog(pmpApiAccessLog, ErrorConstants.STATUS_FAILED, isvalid, responseBody);
						}
						amazonSqsRestTemplate.deleteMessageFromQueue(queueUrl, message);
					} catch (Exception e) {
						LOGGER.error("Scheduler to generate EwelcomeID's : Exception :  {} ",StackTraceUtils.convertStackTracetoString(e));
						String responseBody = "Email:" + participant.getEmail() + " ,EventID:"
								+ participant.getProgram().getAutoGeneratedEventId() + " ,SeqId:"
								+ participant.getSeqId() + " ,EwelcomeID State:" + participant.getEwelcomeIdState()
								+ " ,EwelcomeID informed:" + participant.getIsEwelcomeIdInformed();
						updatePMPAPIAccessLog(pmpApiAccessLog, ErrorConstants.STATUS_FAILED, StackTraceUtils.convertPojoToJson(e), responseBody);
					}

				}
			}
			LOGGER.info("END : EWELCOMEID GENERATION : Scheduler to generate EwelcomeID's for the participants completed at - "+ new Date());
		} else {
			LOGGER.info("END : EWELCOMEID GENERATION : No participants available to generate EwelcomeID's on - " + new Date());
		}
	}

	/**
	 * Method to parse and transform MYSRCM error message.
	 * 
	 * @param eWelcomeID
	 * @return
	 */
	private String transformErrorMsg(String eWelcomeID) {
		String[] eWelcomeIDParts = eWelcomeID.split(" - ");
		if (eWelcomeIDParts[0].equalsIgnoreCase(ErrorConstants.EWELCOMEID_DUPLICATE_RECORD_RESPONSE_FROM_MYSRCM)) {
			eWelcomeIDParts[0] = ErrorConstants.EWELCOMEID_DUPLICATE_RECORD_CUSTOMIZED_RESPONSE;
			eWelcomeID = eWelcomeIDParts[0] + eWelcomeIDParts[1];
		}
		return eWelcomeID;
	}

	//@Scheduled(fixedRate = 120000)//Let say every 2 minutes
	public void pushProgramIdsToAwsSqs() {
		LOGGER.info("Scheduler started to fetch program Id's and sent to SQS");
		String queueName = amazonSqsRestTemplate.getQueuename();
		String queueUrl = "";
		List<Integer> programIds = pgrmRepository.getProgramIdsForSQSPush();
		//amazonSqsRestTemplate.setProxy();
		if(!programIds.isEmpty()){
			queueUrl = amazonSqsRestTemplate.getQueueUrl(queueName);
			for (Integer programId : programIds) {
				try{
					amazonSqsRestTemplate.sendMessageToQueue(queueUrl, String.valueOf(programId));
					LOGGER.info("Program Id - "+programId+" sent to AWS SQS at -"+ new Date());
					pgrmRepository.updateProgramIdStatusAfterSQSPush(programId);
				} catch (Exception ex){
					LOGGER.info("Unable to push program Id {} to queue {}",programId,ex);
				}

			}
		}
		LOGGER.info("Scheduler completed to fetch program Id's and sent to SQS");
	}

	//@Scheduled(fixedRate = 300000)//Let say every 5 minutes
	public void generateEWelcomeIDsForParticipants() {
		LOGGER.info("Scheduler started to pull program Id's from SQS and generating eWelcome Id's");
		List<Integer> programIds;
		String queueUrl = amazonSqsRestTemplate.getQueueUrl(amazonSqsRestTemplate.getQueuename());
		List<Message> sqsMessages = amazonSqsRestTemplate.getMessagesFromQueue(queueUrl);
		LOGGER.info("START : EWELCOMEID GENERATION : Process to generate EwelcomeID's for the participants started at - " + new Date());
		sendMail.sendNotificationToInformProcessExecution(EmailLogConstants.EWELCOME_ID_GENERATION);
		for (Message message : sqsMessages) {
			programIds = new ArrayList<Integer>();
			programIds.add(Integer.parseInt(message.getBody()));
			generateEWelcomeIDsForParticipants(programIds,message,queueUrl);
			programIds.clear();
		}
		LOGGER.info("Scheduler completed to pull program Id's from SQS and generating eWelcome Id's");
	}

	private PMPAPIAccessLog createPMPAPIAccessLog(String username,HttpServletRequest httpRequest,String requestBody){

		PMPAPIAccessLog accessLog = new PMPAPIAccessLog(username, null, 
				"cron-to-generate-ewelcomeID",DateUtils.getCurrentTimeInMilliSec(), null, 
				ErrorConstants.STATUS_FAILED, null,requestBody);
		apiAccessLogService.createPmpAPIAccessLog(accessLog);
		return accessLog;
	}
	private void updatePMPAPIAccessLog(PMPAPIAccessLog pmpApiAccessLog, String status, String errorMessage, String responseBody){

		pmpApiAccessLog.setStatus(status);
		pmpApiAccessLog.setErrorMessage(errorMessage);
		pmpApiAccessLog.setTotalResponseTime(DateUtils.getCurrentTimeInMilliSec());
		pmpApiAccessLog.setResponseBody(responseBody);
		apiAccessLogService.updatePmpAPIAccessLog(pmpApiAccessLog);
	}
}
