package org.srcm.heartfulness.constants;

/**
 * @author Koustav Dutta
 *
 */
public class EmailLogConstants {

	public static final String PCTPT_EMAIL_DETAILS = "PARTICIPANT_DETAILS";
	public static final String WLCMID_EMAIL_DETAILS = "EWELCOME-ID_DETAILS";
	public static final String FTP_UPLOAD_DETAILS = "FTP_UPLOAD";
	public static final String STATUS_SUCCESS = "Success";
	public static final String STATUS_FAILED = "Failed";
	public static final String COORDINATOR_EMAIL_DASHBOARD_LINK = "MAIL_TO_COORDINATOR_WITH_DASHBOARD_LINK";
	public static final String COORDINATOR_EMAIL_CREATE_PROFILE = "MAIL_TO_COORDINATOR_TO_CREATE_PROFILE";
	public static final String EMAIL_CREATE_PROFILE_AND_DASHBOARD_LINK = "MAIL_SENT_TO_PRECEPTOR_AND_COORDINATOR_WITH_CREATE_PROFILE_AND_DASHBOARD_LINK";
	public static final String COORDINATOR_EMAIL_TO_UPDATE_PRECEPTOR_ID= "MAIL_TO_COORDINATOR_TO_UPDATE_PRECEPTOR_ID";
	public static final String PRECEPTOR_EMAIL_TO_UPDATE_COORDINATOR_EMAIL_ID= "MAIL_TO_PRECEPTOR_TO_UPDATE_COORDINATOR_EMAIL_ID";
	
	
	public static final String REQUEST_MAIL_TO_COORDINATOR		= "REQUEST_MAIL_TO_COORDINATOR";
	public static final String REQUEST_MAIL_TO_PRECEPTOR 		= "REQUEST_MAIL_TO_PRECEPTOR";
	public static final String MAIL_TO_SECONDARY_COORDINATOR 	= "MAIL_TO_SECONDARY_COORDINATOR";

}
