package org.srcm.heartfulness.service;

import org.srcm.heartfulness.model.Program;
import org.srcm.heartfulness.model.ProgramCoordinators;
import org.srcm.heartfulness.model.json.response.CoordinatorAccessControlResponse;

/**
 * 
 * @author himasreev
 *
 */
public interface CoordinatorAccessControlService {
	
	public CoordinatorAccessControlResponse addSecondaryCoordinatorRequest(String  autoGeneratedEventId,String userEmail);
	
	public String validatePreceptorIDCardNumberandCreateUser(Program program, int id);

	public String validateCoordinatorEmailID(Program program, int id);

	public void savecoordinatorDetails(ProgramCoordinators programCoordinators);

}
