package org.srcm.heartfulness.service;

import org.springframework.dao.DataAccessException;
import org.srcm.heartfulness.model.Program;

public interface ProgramService {
	
	/**
	 * To create a program and persist
	 * 
	 * @param program - <code>Program</code>
	 * @return the <code>Program</code> 
	 */
	public Program createProgram(Program program);
	
	/**
	 * Check whether program exists or not
	 * 
	 * @param program - <code>Program</code>
	 * @return true or false
	 */
	public boolean isProgramExist(Program program);
	
	/**
	 * Retrieve <code>Program</code> from the data store by Auto generated event id.
	 * 
	 * @param autoGeneratedEventid - Auto generated Event ID to search for
	 * @return the <code>Program</code> if found
	 * @throws DataAccessException
	 */
	Program findByAutoGeneratedEventId(String autoGeneratedEventid) throws DataAccessException;

}
