package org.srcm.heartfulness.validator;

import org.srcm.heartfulness.model.ProgramCoordinators;
import org.srcm.heartfulness.model.json.response.CoordinatorAccessControlErrorResponse;
import org.srcm.heartfulness.model.json.response.CoordinatorAccessControlResponse;

public interface CoordinatorAccessControlValidator {

	CoordinatorAccessControlErrorResponse checkMandatoryFields(String autoGeneratedEventId);

	CoordinatorAccessControlResponse validateCoordinatorRequest(String approvedBy,ProgramCoordinators pgrmCoordinators);
	

}
