ALTER TABLE `program` ADD `coordinator_abhyasi_id` VARCHAR(50) NULL DEFAULT NULL AFTER `coordinator_mobile`,
ADD `coordinator_permission_letter_path` VARCHAR(255) NULL DEFAULT NULL AFTER `coordinator_abhyasi_id`,
ADD `program_zone` VARCHAR(255) NULL DEFAULT NULL AFTER `event_country`,
ADD `program_center` VARCHAR(255) NULL DEFAULT NULL AFTER `program_zone`,
ADD `organization_batch_no` VARCHAR(50) NULL DEFAULT NULL AFTER `organization_web_site`,
ADD `organization_city` VARCHAR(150) NULL DEFAULT NULL AFTER `organization_batch_no`,
ADD `organization_location` VARCHAR(150) NULL DEFAULT NULL AFTER `organization_batch_no`,
ADD `organization_full_address` VARCHAR(255) NULL DEFAULT NULL AFTER `organization_location`,
ADD `organization_decision_maker_name` VARCHAR(150) NULL DEFAULT NULL AFTER `organization_contact_mobile`,
ADD `organization_decision_maker_email` VARCHAR(150) NULL DEFAULT NULL AFTER `organization_decision_maker_name`,
ADD `organization_decision_maker_phone_no` VARCHAR(50) NULL DEFAULT NULL AFTER `organization_decision_maker_email`;